# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: atlassian/default-image:latest

# enable Docker for your repository
options:
  docker: true

pipelines:
  default:
    - step:
        name: Run tests
        image: openjdk:8-jdk-alpine
        script:
          - ./mvnw clean test -Dspring.profiles.active=test
    - step:
        name: Build image
        script:
          - export IMAGE_NAME=tons/docker-oneliner:$BITBUCKET_COMMIT
          - docker build -t $IMAGE_NAME .
    - step:
        name: Push image to docker hub
        script:
          - export IMAGE_NAME=tons/docker-oneliner:$BITBUCKET_COMMIT
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          - docker push $IMAGE_NAME
    - step:
        name: Deploy to heroku
        deployment: test
        script:
          - export IMAGE_NAME=tons/docker-oneliner:$BITBUCKET_COMMIT
          - docker tag $IMAGE_NAME registry.heroku.com/protected-spire-99898/web
          - docker push registry.heroku.com/protected-spire-99898/web
