version: '2'

services:
  backend:
    build: .
    container_name: oneliner-backend
    volumes:
     - ./:/app:Z
     - ~/.m2:/root/.m2:Z
    depends_on:
     - database
    ports:
     - 8080:8080
    environment:
     - SPRING_PROFILES_ACTIVE=docker
     - DATASOURCE_URL=jdbc:postgresql://database:5432/${DB_DATABASE}
     - DATASOURCE_USERNAME=${DB_USERNAME}
     - DATASOURCE_PASSWORD=${DB_PASSWORD}

  database:
    image: postgres:10-beta3-alpine
    container_name: oneliner-database
    environment:
     - POSTGRES_USER=${DB_USERNAME}
     - POSTGRES_PASSWORD=${DB_PASSWORD}
     - POSTGRES_DB=${DB_DATABASE}
