version: '3.4'

services:
  release:
    image: tons/oneliner-backend
    build: .
    depends_on:
     - database
    ports:
     - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
     # The entire url should probably be passed and not just the database name... or not, jdbc, postgresql and the port(?) are static and wont change
      DATASOURCE_URL: jdbc:postgresql://database:5432/${DB_DATABASE}
      DATASOURCE_USERNAME: ${DB_USERNAME}
      DATASOURCE_PASSWORD: ${DB_PASSWORD}

  database:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: ${DB_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
