version: '3.4'

services:
  release:
    image: tons/oneliner-backend:${TAG}
    build: .
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
     # The entire url should probably be passed and not just the database name... or not, jdbc, postgresql and the port(?) are static and wont change
      DATASOURCE_URL: jdbc:postgresql://database:5432/${DB_DATABASE}
      DATASOURCE_USERNAME: ${DB_USERNAME}
      DATASOURCE_PASSWORD: ${DB_PASSWORD}

  database:
    image: postgres:11-alpine
    command: /bin/sh -c "sed -ri \"s/#log_statement = 'none'/log_statement = 'all'/\" /var/lib/postgresql/data/postgresql.conf && su postgres -c postgres"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: ${DB_DATABASE}
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 3

  test:
    image: openjdk:8-jdk-alpine
    working_dir: /src
    volumes:
      - .:/src
    environment:
      SPRING_PROFILES_ACTIVE: test
    command: ./mvnw clean test

volumes:
  database: {}
