server:
  port: 8081

spring:
  application:
    name: OneLiner

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/oneliner
    username: oneliner
    password: oneliner
    driver-class-name: org.postgresql.Driver

---

server:
  port: 8080

spring:
  profiles: docker
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://database:5432/oneliner

---

spring:
  profiles: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver
