server:
  port: 8081

spring:
  application:
    name: OneLiner

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    platform: postgres
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/oneliner}
    username: ${DATASOURCE_USERNAME:oneliner}
    password: ${DATASOURCE_PASSWORD:oneliner}
    driver-class-name: org.postgresql.Driver

---

server:
  port: 8080

spring:
  profiles: docker

  datasource:
    url: ${DATASOURCE_URL}

---

spring:
  profiles: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    platform: h2
#    url: ${DATASOURCE_URL:jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE}
#    username: ${DATASOURCE_USERNAME:sa}
#    password: ${DATASOURCE_PASSWORD:}
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver


---

spring:
  profiles: heroku
  datasource:
    url: ${JDBC_DATABASE_URL}
