server:
  port: 8081

spring:
  application:
    name: OneLiner

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/oneliner
    username: oneliner
    password: oneliner
    driver-class-name: org.postgresql.Driver

---

spring:
  profiles: test
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    password: ""
    driverClassName: org.h2.Driver

#
#merchant:
#  viabill:
#    backend-url: https://secure.viabill.com/api/merchant/account/entries/export/
#    auth-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJDb29sc2hvcCBNYXJrZXRwbGFjZSIsInJvbGVzIjpbIk1FUkNIQU5UIiwiU1lTVEVNIl0sImlkIjo1MDMwLCJ0b2tlblZlcnNpb24iOjEsImlhdCI6MTQ3MDA1NjM4NCwiZXhwIjoxNzg1NTg5MTg0fQ.ncRECmDMJAl3Aujhn_fOjruLLdZPXvJY_YGzD8oYvdo
#    fetcher-cut-off-days: 10
#  hsbc:
#    something: something
