version: 2
jobs:
  build:
    docker:
      - image: tons/dc-ci
    steps:
      - setup_remote_docker
      - checkout
      - run: TAG=snot /build-push.sh

  test:
    docker:
      - image: openjdk:8-jdk-alpine
    steps:
      - checkout
      - run: ./mvnw clean test -Dspring.profiles.active=test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build

# TODO: Branch specific exec and manual approval for realease branch... https://circleci.com/docs/2.0/workflows/
