version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          export IMAGE_NAME=tons/docker-oneliner:$CIRCLE_BUILD_NUM
          docker build -t $IMAGE_NAME .

          export HEROKU_IMAGE_NAME=registry.heroku.com/glacial-spire-56714/web
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          docker tag $IMAGE_NAME $HEROKU_IMAGE_NAME
          docker push $HEROKU_IMAGE_NAME

  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: ./mvnw clean test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
